version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_PB: "http://pocketbase:8090"

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "8090:8090"
