#Stage 02 build pocketbase
FROM alpine:latest

ARG PB_VERSION=0.19.0

RUN apk add --no-cache \
    unzip \
    ca-certificates \
    # this is needed only if you want to use scp to copy later your pb_data locally
    openssh

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v0.21.3/pocketbase_0.21.3_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# uncomment to copy the local pb_migrations dir into the container
COPY ./pb_migrations /pb/pb_migrations


EXPOSE 8081

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8081"]