sonar.projectKey=AndreRimes_onABudget_4fa48a88-5537-4d02-a8bf-c95c1dd7a866
sonar.organization=andrerimes

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/drizzle/**
sonar.sourceEncoding=UTF-8
