
name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted

    steps:
      # Setup virtual env, install dependencies
      - name: Install dependencies 
        run: |
          npm install
          npm run dev
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      # Kill gunicorn server, if running already
      - name: Kill pm2
        run: pm2 del 0

      # Run gunicorn server
      - name: Run pm2
        run: pm2 start "npm run start" --name " onABudget"